### ISSUE TITLE
Не удалось открыть лист KPab_bot по указанному GOOGLE_ID

### ISSUE THREAD

**Issue by vitich** [akokarev/KPab_bot#1]
Здравствуйте. 
Скопировал все листы в новый гугл документ, однако когда делаю сетап нового документа, получаю 
Не удалось открыть лист KPab_bot по указанному GOOGLE_ID

**Comment by akokarev** [comment]
У бота есть своя таблица с настройками - это отдельный файл в таблицах, его ID нужно указать в скрипте. Содержит всего два листа CONFIG и CRON.
Далее создается еще одна таблица с графиками работы в организации. На отдельных листах графики различных отделов.

Так же, в таблице графиков должен быть лист с настройками для этой организации, называется лист KPab_bot, в нем в первых 3х строках шаблоны сообщений (начало и конец) для вчерашнего, сегодняшнего и затрашнего дней соответственно. В столбцах шаблоны для рабочего дня(A), выходного для всех(B). В столбцах (С) и (D) начало и конец строки с названием отдела (так же по строкам вчера, сегодня, завтра).
Начиная со строки 4 пишутся шаблоны которые нужно выводить в сообщениях бота из страниц отелов и формат строки сообщения. В столбце (А) пишется название отдела (листа), либо символ * для всех. В столбце (B) точный текст ячейки (например "Рабочий" или "Выходной"). В столбцах (С) и (D) текст сообщения перед и после фамилии сотрудника.

Еще в новой версии я добавил лист Settings в таблицу с графиками, на работу бота он не влияет, нужен для макроса Formatter, который разукрашивает фон ячеек согласно текста в них.

**Comment by akokarev** [comment]
Проверьте что создали оба файла и прописали в коде ссылку на таблицу с листом KPab_bot

**Comment by vitich** [comment]
Спасибо за ответ, но я так и не понял зачем в файле settings если на самом деле settings вообще в другом файле и т.д. ))) Я пытаюсь ваш файл адаптировать для простейшего графика дежурств - отдел ставит на месяц "+" напротив своей фамилии и на нужную дату известно кто дежурный. Никаких больничных рабочих и т.д.
Если, как Вы говорите, есть отдельный файл настроек+крон, расшарьте пример, без документации трудно догадаться что к чему. Спасибо!

**Comment by vitich** [comment]
Вот текст из самого бота вашего

```
КРаб, [23.04.20 19:20]
Привет! Я бот "Кто работает", скоращенно "КРаб".
Моя задача - отображать список сотрудников на основании графика работы.

График работы - это простая Google таблица, в которой в левой верхней ячейке написана формула =СЕГОДНЯ(), в столбцах указываются фамилии сотрудников, а в строках даты и график работы.
Пример: https://docs.google.com/spreadsheets/d/1bwqL4SBIxtV-z9oQkEetWRXKUb-HIwAIGaMjR03dK7A/edit?usp=sharing

Обрати внимание на служебный лист KPab_bot.
Здесь в первых 3х строках указаны выводимые сообщения для команд yesterday/today/tomorrow(слева направо):
- если кто-то работает в этот день.
- если все отдыхают.
- перед названием отдела(листа) (хочешь стобы писалось с новой строки - введи здесь Ctrl+Enter).
- после названия отдела(листа).
Далее идут шаблоны, которые сравниваются с графиком за текущий день и, если есть совпадение, выводится фамилия сотрудника.
Первый столбец это название листа, к которому будет применяться шаблон. Знак * обозначает любой лист.
Второй столбец это строка поиска. Срабатывает только точное совпадение, шаблоны и подстановочные символы не применимы.
Третий столбец используется перед выводом фамилии сотрудника. Это хорошее место для вставки перевода строки или запятой перед фамилией.
Четвертый столбец выводится после фамилии сотрудника. Здесь удобно вставить закрывающий тег.

Лист Settings необязательный, здесь можно задать цвет фона и текста для наглядного оформления графика. Чтобы изменения вступили в силу, перейди на лист с графиком и запусти макрос Formatter (Инструменты-Макросы-Formatter).)
Чтобы подключиться к существующей таблице выполни команду /setup [GOOGLE_ID].
Например, для подключения демонстрационной таблицы из примера:
/setup 1bwqL4SBIxtV-z9oQkEetWRXKUb-HIwAIGaMjR03dK7A

После установки можешь использовать команду /today для получения списка всех работающих сотрудников на текущий день.
Либо команду /today Техподдержка чтобы узнать только про один отдел.

Аналогичные команды /yesterday и /tomorrow отвечают за вчерашний и завтрашний дни.

Команда /delete удаляетт настройки бота и все задачи cron.


Команда /cron позволит настроить автоматическое выполнение команд в назначенное время.
/cron add "/command" m h d m w - добавит задание на выполнение комманды в указанные минуту час день месяц день_недели. Время указывается в часовом поясе UTC. Используйте подстановочный символ * или пропустите параметр.
Пример: /cron add "/today" 0 6 создаст задачу "/today" на 6:00 UTC (9:00 MSK) ежедневно.
/cron list - выведет список уже существующих заданий.
/cron del [N] - удалит задачу номер N. Порядковый номер можно узнать командой /cron list. Учтите, что после каждого удаления порядковые номера изменяются.
/cron clear - удалит все задачи cron.

(c)2019 @akokarev
https://github.com/akokarev/KPab_bot
2533296@gmail.com
```

**Comment by akokarev** [comment]
Здесь исходники бота, для тех, кто возможно захочет запустить свой отдельный бот. Для такого случая понадобится иметь отдельную таблицу настроек.

Если Вам не принципиально, можете использовать моего бота @KPab_bot, для него я уже создал такую таблицу настроек. В ней храняться ID таблиц и их авторы, в также CRON задачи.
Просто создайте таблицу с граффиком как в примере, укажите боту в комманде /setup ID таблицы, ну и в самой таблице сделайте необходимые настройки. В таблице из примера по-моему все доступно понятно описано, и справка подробная более чем.

**Comment by vitich** [comment]
Так я вашим ботом пытался пользоваться и привязать таблицу...

Пт, 24 квіт. 2020, 22:45 користувач Anton Kokarev <notifications@github.com>
пише:
